server:
  port: 9403
spring:
  application:
    name: provider-message
  cloud:
    client:
      ipAddress: 10.20.2.101
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

