server:
  ipAddress: 10.20.2.101
  port: 8030

spring:
  application:
    name: gateway-zuul


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${server.ipAddress}:${server.port}


zuul:
  routes:
    provider-message: /pro/**
